packages:
    - packages/*

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  ignoreMissing:
    - eslint-plugin-import
    - eslint

allowedDeprecatedVersions:
  source-map-resolve: "*"
  resolve-url: "*"
  source-map-url: "*"
  urix: "*"
  q: "*"

patchedDependencies:
  eslint@9.20.1: patches/eslint@9.20.1.patch
  eslint-plugin-path-alias@2.1.0: patches/eslint-plugin-path-alias@2.1.0.patch