/*
 * Vencord, a modification for Discord's desktop app
 * Copyright (c) 2023 Vendicated and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/*
To generate:
- Visit https://translate.google.com/?sl=auto&tl=en&op=translate
- Open Language dropdown
- Open Devtools and use the element picker to pick the root of the language picker
- Right click on the element in devtools and click "Store as global variable"

copy(Object.fromEntries(
    Array.from(
        temp1.querySelectorAll("[data-language-code]"),
        e => [e.dataset.languageCode, e.children[1].textContent]
    ).sort((a, b) => a[1] === "Detect language" ? -1 : b[1] === "Detect language" ? 1 : a[1].localeCompare(b[1]))
))
*/

export type GoogleLanguage = keyof typeof GoogleLanguages;
export type DeeplLanguage = keyof typeof DeeplLanguages;
export type KagiLanguage = keyof typeof KagiLanguages;

export const GoogleLanguages = {
    "auto": "Detect language",
    "af": "Afrikaans",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "as": "Assamese",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "bm": "Bambara",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bho": "Bhojpuri",
    "bs": "Bosnian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "ny": "Chichewa",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "co": "Corsican",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "dv": "Dhivehi",
    "doi": "Dogri",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "tl": "Filipino",
    "fi": "Finnish",
    "fr": "French",
    "fy": "Frisian",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian Creole",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "iw": "Hebrew",
    "hi": "Hindi",
    "hmn": "Hmong",
    "hu": "Hungarian",
    "is": "Icelandic",
    "ig": "Igbo",
    "ilo": "Ilocano",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "jw": "Javanese",
    "kn": "Kannada",
    "kk": "Kazakh",
    "km": "Khmer",
    "rw": "Kinyarwanda",
    "gom": "Konkani",
    "ko": "Korean",
    "kri": "Krio",
    "ku": "Kurdish (Kurmanji)",
    "ckb": "Kurdish (Sorani)",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "la": "Latin",
    "lv": "Latvian",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lg": "Luganda",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "mai": "Maithili",
    "mg": "Malagasy",
    "ms": "Malay",
    "ml": "Malayalam",
    "mt": "Maltese",
    "mi": "Maori",
    "mr": "Marathi",
    "mni-Mtei": "Meiteilon (Manipuri)",
    "lus": "Mizo",
    "mn": "Mongolian",
    "my": "Myanmar (Burmese)",
    "ne": "Nepali",
    "no": "Norwegian",
    "or": "Odia (Oriya)",
    "om": "Oromo",
    "ps": "Pashto",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi",
    "qu": "Quechua",
    "ro": "Romanian",
    "ru": "Russian",
    "sm": "Samoan",
    "sa": "Sanskrit",
    "gd": "Scots Gaelic",
    "nso": "Sepedi",
    "sr": "Serbian",
    "st": "Sesotho",
    "sn": "Shona",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "es": "Spanish",
    "su": "Sundanese",
    "sw": "Swahili",
    "sv": "Swedish",
    "tg": "Tajik",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "th": "Thai",
    "ti": "Tigrinya",
    "ts": "Tsonga",
    "tr": "Turkish",
    "tk": "Turkmen",
    "ak": "Twi",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ug": "Uyghur",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "zu": "Zulu"
} as const;

export const DeeplLanguages = {
    "": "Detect language",
    "ar": "Arabic",
    "bg": "Bulgarian",
    "zh-hans": "Chinese (Simplified)",
    "zh-hant": "Chinese (Traditional)",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en-us": "English (American)",
    "en-gb": "English (British)",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "el": "Greek",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "nb": "Norwegian",
    "pl": "Polish",
    "pt-br": "Portuguese (Brazilian)",
    "pt-pt": "Portuguese (European)",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sv": "Swedish",
    "tr": "Turkish",
    "uk": "Ukrainian"
} as const;

export function deeplLanguageToGoogleLanguage(language: string) {
    switch (language) {
        case "": return "auto";
        case "nb": return "no";
        case "zh-hans": return "zh-CN";
        case "zh-hant": return "zh-TW";
        case "en-us":
        case "en-gb":
            return "en";
        case "pt-br":
        case "pt-pt":
            return "pt";
        default:
            return language;
    }
}

// Generated using:
// curl https://translate.kagi.com/api/list-languages | jq 'map({(.language | ascii_downcase): .name}) | add'
// Add "auto": "Detect language", as kagi has no "language" for Detect Language, however anything not
// in the list will work as auto. Using "auto" will have this work using Google Translate defaults.
// Retrieved 2025.06.11
export const KagiLanguages = {
    "auto": "Detect language",
    "om": "(Afan)/Oromoor/Oriya",
    "ab": "Abkhazian",
    "ace": "Acehnese",
    "ach": "Acholi",
    "af": "Afrikaans",
    "am": "Amharic",
    "ak": "Akan",
    "sq": "Albanian",
    "de_de": "German (Germany)",
    "de": "German",
    "de_li": "German (Liechtenstein)",
    "de_lu": "German (Luxembourg)",
    "de_ch": "Swiss High German",
    "gsw": "Swiss German",
    "alz": "Alur",
    "en": "English",
    "en_za": "English (South Africa)",
    "en_au": "English (Australia)",
    "en_ca": "English (Canada)",
    "en_in": "English (India)",
    "en_ie": "English (Ireland)",
    "en_nz": "English (New Zealand)",
    "en_ph": "English (Philippines)",
    "en_sg": "English (Singapore)",
    "en_gb": "English (UK)",
    "en_us": "English (US)",
    "ar": "Arabic",
    "ar_dz": "Arabic (Algeria)",
    "ar_sa": "Arabic (Saudi Arabia)",
    "ar_ae": "Arabic (UAE)",
    "ar_eg": "Arabic (Egypt)",
    "ar_iq": "Arabic (Iraq)",
    "ar_jo": "Arabic (Jordan)",
    "ar_kw": "Arabic (Kuwait)",
    "ar_lb": "Arabic (Lebanon)",
    "ar_ly": "Arabic (Libya)",
    "ar_ma": "Arabic (Morocco)",
    "ar_qa": "Arabic (Qatar)",
    "ar_sy": "Arabic (Syria)",
    "ar_tn": "Arabic (Tunisia)",
    "an": "Aragonese",
    "hy": "Armenian",
    "as": "Assamese",
    "de_at": "German (Austria)",
    "av": "Avaric",
    "ae": "Avestan",
    "ava": "Awadhi",
    "ay": "Aymara",
    "az": "Azeri",
    "ba": "Bashkir",
    "ban": "Balinese",
    "bal": "Baluchi",
    "bm": "Bambara",
    "bci": "Baoulé",
    "eu": "Basque",
    "btk": "Batak",
    "bem": "Bemba",
    "bn": "Bengali",
    "bn_bd": "Bengali (Bangladesh)",
    "bn_in": "Bengali (India)",
    "bew": "Betawi",
    "bho": "Bhojpuri",
    "dz": "Bhutani",
    "bi": "Bislama",
    "be": "Belarusian",
    "bh": "Bihari",
    "bcl": "Bikol",
    "my": "Burmese",
    "bs": "Bosnian",
    "bua": "Buryat",
    "ee": "Ewe",
    "br": "Breton",
    "bg": "Bulgarian",
    "ks": "Kashmiri",
    "km": "Cambodian",
    "yue": "Cantonese",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "ch": "Chamorro",
    "chr": "Cherokee",
    "ny": "Chichewa",
    "zh": "Chinese",
    "zh_hk": "Chinese (Hong Kong)",
    "zh_mo": "Chinese (Macau)",
    "zh_sg": "Chinese (Singapore)",
    "zh_tw": "Chinese (Traditional)",
    "zh_cn": "Chinese (Simplified)",
    "si": "Singhalese",
    "kg": "Kongo",
    "ko": "Korean",
    "ko_kp": "Korean (North Korea)",
    "ko_kr": "Korean (South Korea)",
    "kw": "Cornish",
    "co": "Corsican",
    "cr": "Cree",
    "hr": "Croatian",
    "hr_ba": "Croatian (Bosnia and Herzegovina)",
    "hr_hr": "Croatian (Croatia)",
    "da": "Danish",
    "din": "Dinka",
    "dyu": "Dyula",
    "div": "Divehi",
    "dv": "Divehi",
    "doi": "Dogri",
    "dov": "Dombe",
    "gd": "Gaelic",
    "elvish": "Elvish (Sindarin)",
    "es": "Spanish",
    "es_ar": "Spanish (Argentina)",
    "es_bo": "Spanish (Bolivia)",
    "es_cl": "Spanish (Chile)",
    "es_co": "Spanish (Colombia)",
    "es_cr": "Spanish (Costa Rica)",
    "es_cu": "Spanish (Cuba)",
    "es_ec": "Spanish (Ecuador)",
    "es_es": "Spanish (Spain)",
    "es_gt": "Spanish (Guatemala)",
    "es_gq": "Spanish (Equatorial Guinea)",
    "es_hn": "Spanish (Honduras)",
    "es_mx": "Spanish (Mexico)",
    "es_ni": "Spanish (Nicaragua)",
    "es_pa": "Spanish (Panama)",
    "es_py": "Spanish (Paraguay)",
    "es_pe": "Spanish (Peru)",
    "es_pr": "Spanish (Puerto Rico)",
    "es_do": "Spanish (Dominican Republic)",
    "es_sv": "Spanish (El Salvador)",
    "es_uy": "Spanish (Uruguay)",
    "es_ve": "Spanish (Venezuela)",
    "eo": "Esperanto",
    "et": "Estonian",
    "fa": "Farsi",
    "fo": "Faroese",
    "fj": "Fiji",
    "fi": "Finnish",
    "fon": "Fon",
    "fr": "French",
    "fr_be": "French (Belgium)",
    "fr_ca": "French (Canada)",
    "fr_ci": "French (Côte d'Ivoire)",
    "fr_fr": "French (France)",
    "fr_sn": "French (Senegal)",
    "fr_ch": "French (Switzerland)",
    "fur": "Friulian",
    "fy": "Frisian",
    "gl": "Galician",
    "gaa": "Ga",
    "cy": "Welsh",
    "lg": "Ganda",
    "ka": "Georgian",
    "el": "Greek",
    "kl": "Greenlandic",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "hz": "Herero",
    "hil": "Hiligaynon",
    "hi": "Hindi",
    "hi_in": "Hindi (India)",
    "hi_fj": "Hindi (Fiji)",
    "ho": "Hiri Motu",
    "hu": "Hungarian",
    "hrx": "Hunsrik",
    "iba": "Iban",
    "io": "Ido",
    "ig": "Igbo",
    "ilo": "Ilocano",
    "sx": "Sutu",
    "id": "Indonesian",
    "ia": "Interlingua",
    "ie": "Interlingue",
    "iu": "Inuktitut",
    "ik": "Inupiak",
    "ga": "Irish",
    "is": "Icelandic",
    "it_it": "Italian (Italy)",
    "it": "Italian",
    "it_va": "Italian (Vatican City)",
    "it_sm": "Italian (San Marino)",
    "ja": "Japanese",
    "jv": "Javanese",
    "cpe": "Jingpo",
    "kn": "Kannada",
    "kr": "Kanuri",
    "kk": "Kazakh",
    "kha": "Khasi",
    "ki": "Kikuyu",
    "rw": "Kinyarwanda",
    "ky": "Kirghiz",
    "rn": "Kirundi",
    "ktu": "Kituba",
    "klingon": "Klingon",
    "kv": "Komi",
    "kok": "Konkani",
    "kj": "Kuanyama",
    "ku": "Kurdish",
    "ckb": "Kurdish (Sorani)",
    "emoji": "Emoji Speak",
    "lo": "Laothian",
    "la": "Latin",
    "ltg": "Latgalian",
    "lv": "Latvian",
    "lij": "Ligurian",
    "li": "Limburgan",
    "lim": "Limburgish",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "aa": "Afar",
    "lmo": "Lombard",
    "lu": "Luba_Katanga",
    "luo": "Luo",
    "lb": "Luxembourgish",
    "mk": "FYRO Macedonian",
    "mad": "Madurese",
    "mai": "Maithili",
    "mak": "Makassar",
    "ms": "Malay",
    "ms_bn": "Malay (Brunei Darussalam)",
    "ms_id": "Malay (Indonesia)",
    "ms_arab": "Malay (Jawi)",
    "ms_my": "Malay (Malaysia)",
    "ms_sg": "Malay (Singapore)",
    "ml": "Malayalam",
    "mg": "Malagasy",
    "mt": "Maltese",
    "gv": "Manx",
    "mi": "Maori",
    "mr": "Marathi",
    "mh": "Marshallese",
    "mwr": "Marwadi",
    "yua": "Yucatec Maya",
    "mo": "Moldavian",
    "mn": "Mongolian",
    "middle_english": "Middle English",
    "nqo": "NKo",
    "nhe": "Nahuatl",
    "na": "Nauru",
    "nv": "Navajo",
    "ndc": "Ndau",
    "nd": "North Ndebele",
    "nr": "South Ndebele",
    "ng": "Ndonga",
    "nl": "Dutch",
    "nl_aw": "Dutch (Aruba)",
    "nl_be": "Dutch (Belgium)",
    "nl_cw": "Dutch (Curaçao)",
    "nl_nl": "Dutch (Netherlands)",
    "nl_sr": "Dutch (Suriname)",
    "ne": "Nepali",
    "new": "Nepalbhasa",
    "nb": "Norwegian (Bokmål)",
    "nn": "Norwegian (Nynorsk)",
    "nus": "Nuer",
    "oc": "Occitan",
    "oj": "Ojibwa",
    "or": "Oriya",
    "os": "Ossetian",
    "udm": "Udmurt",
    "ug": "Uighur",
    "ur": "Urdu",
    "ur_in": "Urdu (India)",
    "ur_pk": "Urdu (Pakistan)",
    "uz": "Uzbek",
    "ps": "Pashto/Pushto",
    "pi": "Pali",
    "pag": "Pangasinan",
    "pa": "Punjabi",
    "pap": "Papiamento",
    "pirate": "Pirate Speak",
    "jam": "Jamaican Patois",
    "per": "Persian",
    "fa_af": "Persian (Afghanistan)",
    "fa_ir": "Persian (Iran)",
    "fa_tj": "Persian (Tajikistan)",
    "ff": "Fulah",
    "fil": "Filipino",
    "pl": "Polish",
    "pt": "Portuguese",
    "pt_ao": "Portuguese (Angola)",
    "pt_br": "Portuguese (Brazil)",
    "pt_cv": "Portuguese (Cape Verde)",
    "pt_mz": "Portuguese (Mozambique)",
    "pt_pt": "Portuguese (Portugal)",
    "qu": "Quechua",
    "qu_bo": "Quechua (Bolivia)",
    "qu_ec": "Quechua (Ecuador)",
    "qu_pe": "Quechua (Peru)",
    "kek": "Qʼeqchiʼ",
    "rm": "Rhaeto_Romanic",
    "rom": "Romani",
    "ro": "Romanian",
    "ru": "Russian",
    "ru_by": "Russian (Belarus)",
    "ru_kz": "Russian (Kazakhstan)",
    "ru_kg": "Russian (Kyrgyzstan)",
    "ru_ru": "Russian (Russia)",
    "se": "Sami",
    "se_fi": "Sami (Finland)",
    "se_no": "Sami (Norway)",
    "se_se": "Sami (Sweden)",
    "sm": "Samoan",
    "sg": "Sangro",
    "sa": "Sanskrit",
    "sat": "Santali",
    "sc": "Sardinian",
    "sr": "Serbian",
    "sr_ba": "Serbian (Bosnia and Herzegovina)",
    "sr_sp": "Serbian (Serbia and Montenegro)",
    "sh": "Serbo_Croatian",
    "shn": "Shan",
    "sn": "Shona",
    "scn": "Sicilian",
    "szl": "Silesian",
    "sd": "Sindhi",
    "ss": "Siswati",
    "cu": "Church Slavonic",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "sb": "Sorbian",
    "st": "Sesotho",
    "ns": "Northern Sotho",
    "su": "Sundanese",
    "sv_se": "Swedish (Sweden)",
    "sv": "Swedish",
    "sv_fi": "Swedish (Finland)",
    "it_ch": "Italian (Switzerland)",
    "sw": "Swahili",
    "syr": "Syriac",
    "tg": "Tajik",
    "tl": "Tagalog",
    "ty": "Tahitian",
    "ta": "Tamil",
    "ta_in": "Tamil (India)",
    "ta_my": "Tamil (Malaysia)",
    "ta_sg": "Tamil (Singapore)",
    "ta_lk": "Tamil (Sri Lanka)",
    "tt": "Tatar",
    "crh": "Crimean Tatar",
    "cs": "Czech",
    "ce": "Chechen",
    "cv": "Chuvash",
    "te": "Telugu",
    "tet": "Tetum",
    "th": "Thai",
    "bo": "Tibetan",
    "ti": "Tigrinya",
    "tiv": "Tiv",
    "tpi": "Tok Pisin",
    "to": "Tonga",
    "sus": "Susu",
    "tyv": "Tuvan",
    "chk": "Chuukese",
    "ts": "Tsonga",
    "tn": "Tswana",
    "tum": "Tumbuka",
    "tr": "Turkish",
    "tr_cy": "Turkish (Cyprus)",
    "tr_tr": "Turkish (Turkey)",
    "tk": "Turkmen",
    "tw": "Twi",
    "uk": "Ukrainian",
    "ve": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "vo": "Volapuk",
    "wa": "Walloon",
    "war": "Waray",
    "wo": "Wolof",
    "xh": "Xhosa",
    "sah": "Yakut",
    "ii": "Sichuan Yi",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "zap": "Zapotec",
    "za": "Zhuang",
    "zu": "Zulu"
} as const;
