/*
 * Vencord, a modification for Discord's desktop app
 * Copyright (c) 2023 Vendicated and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/*
To generate:
- Visit https://translate.google.com/?sl=auto&tl=en&op=translate
- Open Language dropdown
- Open Devtools and use the element picker to pick the root of the language picker
- Right click on the element in devtools and click "Store as global variable"

copy(Object.fromEntries(
    Array.from(
        temp1.querySelectorAll("[data-language-code]"),
        e => [e.dataset.languageCode, e.children[1].textContent]
    ).sort((a, b) => a[1] === "Detect language" ? -1 : b[1] === "Detect language" ? 1 : a[1].localeCompare(b[1]))
))
*/

export type GoogleLanguage = keyof typeof GoogleLanguages;
export type DeeplLanguage = keyof typeof DeeplLanguages;
export type KagiLanguage = keyof typeof KagiLanguages;

export const GoogleLanguages = {
    "auto": "Detect language",
    "af": "Afrikaans",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "as": "Assamese",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "bm": "Bambara",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bho": "Bhojpuri",
    "bs": "Bosnian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "ny": "Chichewa",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "co": "Corsican",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "dv": "Dhivehi",
    "doi": "Dogri",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "tl": "Filipino",
    "fi": "Finnish",
    "fr": "French",
    "fy": "Frisian",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian Creole",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "iw": "Hebrew",
    "hi": "Hindi",
    "hmn": "Hmong",
    "hu": "Hungarian",
    "is": "Icelandic",
    "ig": "Igbo",
    "ilo": "Ilocano",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "jw": "Javanese",
    "kn": "Kannada",
    "kk": "Kazakh",
    "km": "Khmer",
    "rw": "Kinyarwanda",
    "gom": "Konkani",
    "ko": "Korean",
    "kri": "Krio",
    "ku": "Kurdish (Kurmanji)",
    "ckb": "Kurdish (Sorani)",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "la": "Latin",
    "lv": "Latvian",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lg": "Luganda",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "mai": "Maithili",
    "mg": "Malagasy",
    "ms": "Malay",
    "ml": "Malayalam",
    "mt": "Maltese",
    "mi": "Maori",
    "mr": "Marathi",
    "mni-Mtei": "Meiteilon (Manipuri)",
    "lus": "Mizo",
    "mn": "Mongolian",
    "my": "Myanmar (Burmese)",
    "ne": "Nepali",
    "no": "Norwegian",
    "or": "Odia (Oriya)",
    "om": "Oromo",
    "ps": "Pashto",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi",
    "qu": "Quechua",
    "ro": "Romanian",
    "ru": "Russian",
    "sm": "Samoan",
    "sa": "Sanskrit",
    "gd": "Scots Gaelic",
    "nso": "Sepedi",
    "sr": "Serbian",
    "st": "Sesotho",
    "sn": "Shona",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "es": "Spanish",
    "su": "Sundanese",
    "sw": "Swahili",
    "sv": "Swedish",
    "tg": "Tajik",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "th": "Thai",
    "ti": "Tigrinya",
    "ts": "Tsonga",
    "tr": "Turkish",
    "tk": "Turkmen",
    "ak": "Twi",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ug": "Uyghur",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "zu": "Zulu"
} as const;

export const DeeplLanguages = {
    "": "Detect language",
    "ar": "Arabic",
    "bg": "Bulgarian",
    "zh-hans": "Chinese (Simplified)",
    "zh-hant": "Chinese (Traditional)",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en-us": "English (American)",
    "en-gb": "English (British)",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "el": "Greek",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "nb": "Norwegian",
    "pl": "Polish",
    "pt-br": "Portuguese (Brazilian)",
    "pt-pt": "Portuguese (European)",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sv": "Swedish",
    "tr": "Turkish",
    "uk": "Ukrainian"
} as const;

export function deeplLanguageToGoogleLanguage(language: string) {
    switch (language) {
        case "": return "auto";
        case "nb": return "no";
        case "zh-hans": return "zh-CN";
        case "zh-hant": return "zh-TW";
        case "en-us":
        case "en-gb":
            return "en";
        case "pt-br":
        case "pt-pt":
            return "pt";
        default:
            return language;
    }
}

export const KagiLanguages = {
    "und": "Undetermined",
    "proofread": "Proofread (spelling & grammar)",
    "auto": "Detect Language",
    "elvish": "Elvish (Sindarin)",
    "emoji": "Emoji Speak",
    "klingon": "Klingon",
    "middle_english": "Middle English",
    "pirate": "Pirate Speak",
    "aa": "Afar",
    "ab": "Abkhazian",
    "ace": "Acehnese",
    "ach": "Acholi",
    "ae": "Avestan",
    "af": "Afrikaans",
    "alz": "Alur",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "as": "Assamese",
    "ava": "Awadhi",
    "av": "Avaric",
    "ay": "Aymara",
    "az": "Azeri",
    "ba": "Bashkir",
    "bal": "Baluchi",
    "ban": "Balinese",
    "bci": "Baoulé",
    "be": "Belarusian",
    "bem": "Bemba",
    "bew": "Betawi",
    "bg": "Bulgarian",
    "bh": "Bihari",
    "bho": "Bhojpuri",
    "bi": "Bislama",
    "bcl": "Bikol",
    "bm": "Bambara",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "btk": "Batak",
    "bua": "Buryat",
    "ca": "Catalan",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "ch": "Chamorro",
    "chk": "Chuukese",
    "co": "Corsican",
    "ckb": "Kurdish (Sorani)",
    "cpe": "Jingpo",
    "crh": "Crimean Tatar",
    "cr": "Cree",
    "cs": "Czech",
    "cu": "Church Slavonic",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de_at": "German (Austria)",
    "de_ch": "Swiss High German",
    "de_de": "German (Germany)",
    "de_li": "German (Liechtenstein)",
    "de_lu": "German (Luxembourg)",
    "de": "German",
    "din": "Dinka",
    "dv": "Divehi",
    "doi": "Dogri",
    "dov": "Dombe",
    "dyu": "Dyula",
    "dz": "Bhutani",
    "ee": "Ewe",
    "el": "Greek",
    "en": "English",
    "en_au": "English (Australia)",
    "en_ca": "English (Canada)",
    "en_gb": "English (UK)",
    "en_us": "English (US)",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Farsi",
    "ff": "Fulah",
    "fi": "Finnish",
    "fil": "Filipino",
    "fj": "Fiji",
    "fo": "Faroese",
    "fon": "Fon",
    "fr_ca": "French (Canada)",
    "fr": "French",
    "fur": "Friulian",
    "fy": "Frisian",
    "ga": "Irish",
    "gaa": "Ga",
    "gd": "Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gu": "Gujarati",
    "gsw": "Swiss German",
    "gv": "Manx",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "iw": "Hebrew",
    "hi": "Hindi",
    "hil": "Hiligaynon",
    "ho": "Hiri Motu",
    "hr_ba": "Croatian (Bosnia and Herzegovina)",
    "hr_hr": "Croatian (Croatia)",
    "hr": "Croatian",
    "hrx": "Hunsrik",
    "ht": "Haitian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "hz": "Herero",
    "ia": "Interlingua",
    "iba": "Iban",
    "in": "Indonesian",
    "ie": "Interlingue",
    "ig": "Igbo",
    "ii": "Sichuan Yi",
    "ik": "Inupiak",
    "ilo": "Ilocano",
    "io": "Ido",
    "is": "Icelandic",
    "it_ch": "Italian (Switzerland)",
    "it_it": "Italian (Italy)",
    "it": "Italian",
    "iu": "Inuktitut",
    "ja": "Japanese",
    "jam": "Jamaican Patois",
    "jv": "Javanese",
    "ka": "Georgian",
    "kg": "Kongo",
    "kek": "Qʼeqchiʼ",
    "kha": "Khasi",
    "ki": "Kikuyu",
    "kj": "Kuanyama",
    "kk": "Kazakh",
    "kl": "Greenlandic",
    "km": "Cambodian",
    "kn": "Kannada",
    "ko": "Korean",
    "kok": "Konkani",
    "kr": "Kanuri",
    "ks": "Kashmiri",
    "ktu": "Kituba",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kirghiz",
    "kz": "Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lg": "Ganda",
    "li": "Limburgan",
    "lij": "Ligurian",
    "lim": "Limburgish",
    "ln": "Lingala",
    "lo": "Laothian",
    "lmo": "Lombard",
    "lt": "Lithuanian",
    "ltg": "Latgalian",
    "lu": "Luba_Katanga",
    "luo": "Luo",
    "lv": "Latvian",
    "mad": "Madurese",
    "mai": "Maithili",
    "mak": "Makassar",
    "mg": "Malagasy",
    "mh": "Marshallese",
    "mi": "Maori",
    "mk": "FYRO Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mo": "Moldavian",
    "mr": "Marathi",
    "ms_arab": "Malay (Jawi)",
    "ms_bn": "Malay (Brunei Darussalam)",
    "ms_my": "Malay (Malaysia)",
    "ms": "Malay",
    "mt": "Maltese",
    "mwr": "Marwadi",
    "my": "Burmese",
    "na": "Nauru",
    "nb": "Norwegian (Bokmål)",
    "nd": "North Ndebele",
    "ndc": "Ndau",
    "ne": "Nepali",
    "new": "Nepalbhasa",
    "ng": "Ndonga",
    "nhe": "Nahuatl",
    "nl_be": "Dutch (Belgium)",
    "nl_nl": "Dutch (Netherlands)",
    "nl": "Dutch",
    "nn": "Norwegian (Nynorsk)",
    "nqo": "NKo",
    "nr": "South Ndebele",
    "ns": "Northern Sotho",
    "nus": "Nuer",
    "nv": "Navajo",
    "ny": "Chichewa",
    "oc": "Occitan",
    "oj": "Ojibwa",
    "om": "(Afan)/Oromoor/Oriya",
    "or": "Oriya",
    "os": "Ossetian",
    "pa": "Punjabi",
    "pag": "Pangasinan",
    "pap": "Papiamento",
    "pi": "Pali",
    "pl": "Polish",
    "ps": "Pashto/Pushto",
    "pt_br": "Portuguese (Brazil)",
    "pt_pt": "Portuguese (Portugal)",
    "pt": "Portuguese",
    "qu_bo": "Quechua (Bolivia)",
    "qu_ec": "Quechua (Ecuador)",
    "qu_pe": "Quechua (Peru)",
    "qu": "Quechua",
    "rm": "Rhaeto_Romanic",
    "rn": "Kirundi",
    "ro": "Romanian",
    "rom": "Romani",
    "ru": "Russian",
    "rw": "Kinyarwanda",
    "sa": "Sanskrit",
    "sah": "Yakut",
    "sat": "Santali",
    "sb": "Sorbian",
    "sc": "Sardinian",
    "scn": "Sicilian",
    "sd": "Sindhi",
    "se_fi": "Sami (Finland)",
    "se_no": "Sami (Norway)",
    "se_se": "Sami (Sweden)",
    "se": "Sami",
    "sg": "Sangro",
    "sh": "Serbo_Croatian",
    "shn": "Shan",
    "si": "Singhalese",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sm": "Samoan",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr_ba": "Serbian (Bosnia and Herzegovina)",
    "sr_sp": "Serbian (Serbia and Montenegro)",
    "sr": "Serbian",
    "ss": "Siswati",
    "st": "Sesotho",
    "su": "Sundanese",
    "sus": "Susu",
    "sv_fi": "Swedish (Finland)",
    "sv_se": "Swedish (Sweden)",
    "sv": "Swedish",
    "sw": "Swahili",
    "sx": "Sutu",
    "syr": "Syriac",
    "szl": "Silesian",
    "ta": "Tamil",
    "te": "Telugu",
    "tet": "Tetum",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tiv": "Tiv",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tn": "Tswana",
    "to": "Tonga",
    "tpi": "Tok Pisin",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "tum": "Tumbuka",
    "tw": "Twi",
    "ty": "Tahitian",
    "tyv": "Tuvan",
    "udm": "Udmurt",
    "ug": "Uighur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "ve": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "vo": "Volapuk",
    "wa": "Walloon",
    "war": "Waray",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yua": "Yucatec Maya",
    "za": "Zhuang",
    "zap": "Zapotec",
    "zh": "Chinese",
    "zh_cn": "Chinese (Simplified)",
    "zh_tw": "Chinese (Traditional)",
    "yue": "Cantonese",
    "zu": "Zulu"
} as const;
