export const enum QuestRewardType {
    REWARD_CODE = 1,
    IN_GAME = 2,
    COLLECTIBLE = 3,
    VIRTUAL_CURRENCY = 4,
    FRACTIONAL_PREMIUM = 5,
}

export const enum QuestPlatform {
    CROSS_PLATFORM = 0,
    XBOX = 1,
    PLAYSTATION = 2,
    SWITCH = 3,
    PC = 4,
}

export const enum QuestTargetedContent {
    GIFT_INVENTORY_SETTINGS_BADGE = 0,
    QUEST_BAR = 1,
    QUEST_INVENTORY_CARD = 2,
    QUESTS_EMBED = 3,
    ACTIVITY_PANEL = 4,
    QUEST_LIVE_STREAM = 5,
    MEMBERS_LIST = 6,
    QUEST_BADGE = 7,
    GIFT_INVENTORY_FOR_YOU = 8,
    GIFT_INVENTORY_OTHER = 9,
    QUEST_BAR_V2 = 10,
    QUEST_HOME_DESKTOP = 11,
    QUEST_HOME_MOBILE = 12,
    QUEST_BAR_MOBILE = 13,
    THIRD_PARTY_APP = 14,
    QUEST_BOTTOM_SHEET = 15,
    QUEST_EMBED_MOBILE = 16,
    QUEST_HOME_MOVE_CALLOUT = 17,
    DISCOVERY_SIDEBAR = 18,
    QUEST_SHARE_LINK = 19,
    CONNECTIONS_MODAL = 20,
    DISCOVERY_COMPASS = 21,
    TROPHY_CASE_CARD = 22,
    VIDEO_MODAL = 23,
    VIDEO_MODAL_END_CARD = 24,
    REWARD_MODAL = 25,
    EXCLUDED_QUEST_EMBED = 26,
    VIDEO_MODAL_MOBILE = 27,
    ORBS_ANNOUNCEMENT_MODAL = 28,
    ORBS_BALANCE_MENU = 29,
    QUEST_ENROLLMENT_BLOCKED_BOTTOM_SHEET = 30,
    ORBS_SHOP_HERO_CTA = 31,
    QUEST_ENROLLMENT_BLOCKED_MODAL = 32,
    INTERNAL_PREVIEW_TOOL = 33,
    ORBS_REHEAT_COACHMARK_CTA = 34,
    INVALID_QUEST_EMBED = 35,
    NOT_SHAREABLE_QUEST_EMBED = 36,
    QUEST_HOME_MOVE_CALLOUT_DISCOVER = 37,
    SPONSORED_QUEST_SHEET = 38,
    MOBILE_ORBS_ONBOARDING_DC = 39,
    RUNNING_ACTIVITY = 40,
    VIDEO_MODAL_PRIMARY_CTA = 41,
    QUEST_HOME_TAKEOVER = 42,
    USER_PROFILE_ACTIVITY = 43,
}

export const enum QuestPlacement {
    INVALID_PLACEMENT = 0,
    DESKTOP_ACCOUNT_PANEL_AREA = 1,
    MOBILE_HOME_DOCK_AREA = 2,
}

export const enum QuestRewardAssignmentMethod {
    ALL = 1,
    TIERED = 2,
}

export const enum QuestRewardExpirationMode {
    NORMAL = 1,
    PREMIUM_EXTENSION = 2,
    PREMIUM_PERMANENT = 3,
}

export const enum QuestFeature {
    POST_ENROLLMENT_CTA = 1,
    QUEST_BAR_V2 = 3,
    EXCLUDE_RUSSIA = 5,
    IN_HOUSE_CONSOLE_QUEST = 6,
    MOBILE_CONSOLE_QUEST = 7,
    START_QUEST_CTA = 8,
    REWARD_HIGHLIGHTING = 9,
    FRACTIONS_QUEST = 10,
    ADDITIONAL_REDEMPTION_INSTRUCTIONS = 11,
    PACING_V2 = 12,
    DISMISSAL_SURVEY = 13,
    MOBILE_QUEST_DOCK = 14,
    QUESTS_CDN = 15,
    PACING_CONTROLLER = 16,
    QUEST_HOME_FORCE_STATIC_IMAGE = 17,
    VIDEO_QUEST_FORCE_HLS_VIDEO = 18,
    VIDEO_QUEST_FORCE_END_CARD_CTA_SWAP = 19,
    EXPERIMENTAL_TARGETING_TRAITS = 20,
    DO_NOT_DISPLAY = 21,
    EXTERNAL_DIALOG = 22,
    MOBILE_ONLY_QUEST_PUSH_TO_MOBILE = 23,
    MANUAL_HEARTBEAT_INITIALIZATION = 24,
    CLOUD_GAMING_ACTIVITY = 25,
    NON_GAMING_PLAY_QUEST = 26,
    ACTIVITY_QUEST_AUTO_ENROLLMENT = 27,
    PACKAGE_ACTION_ADVENTURE = 28,
    PACKAGE_RPG_MMO = 29,
    PACKAGE_RACING_SPORTS = 30,
    PACKAGE_SANDBOX_CREATIVE = 31,
    PACKAGE_FAMILY_FRIENDLY = 32,
    PACKAGE_HOLIDAY_SEASON = 33,
    PACKAGE_NEW_YEARS = 34,
}

export const enum QuestDismissibleContentFlags {
    GIFT_INVENTORY_SETTINGS_BADGE = 1,
    QUEST_BAR = 2,
    ACTIVITY_PANEL = 4,
    QUEST_LIVE_STREAM = 8,
}

export const enum QuestUserQuestStatus {
    UNACCEPTED = 0,
    ACCEPTED = 1,
    IN_PROGRESS = 2,
    COMPLETED = 3,
    CLAIMED = 4,
}
