name: Blank Issue
description: Create a blank issue. ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING AN ISSUE

        This form is ONLY FOR DEVELOPERS. YOUR ISSUE WILL BE CLOSED AND YOU WILL POSSIBLY BE BLOCKED FROM THE REPOSITORY IF YOU IGNORE THIS.
        
        DO NOT USE THIS FORM, unless
        - you are a vencord contributor
        - you were given explicit permission to use this form by a moderator in our support server
        
        DO NOT USE THIS FORM FOR SECURITY RELATED ISSUES. [CREATE A SECURITY ADVISORY INSTEAD.](https://github.com/Vendicated/Vencord/security/advisories/new)

  - type: textarea
    id: content
    attributes:
      label: Content
    validations:
      required: true

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      options:
        - label: I have read the requirements for opening an issue above
          required: true
