name: Bug/Crash Report
description: Create a bug or crash report for Vencord
labels: [bug]

body:
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required but encouraged for easier follow-up
      placeholder: username#0000
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: What happens when the bug or crash occurs?
      description: Where does this bug or crash occur, when does it occur, etc.
      placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ...
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: Simply detail what the expected behaviour is.
      placeholder: I expect Vencord/Discord to open the ... page instead of ..., it prevents me from doing ...
    validations:
      required: true

  - type: textarea
    id: steps-to-take
    attributes:
      label: How do you recreate this bug or crash?
      description: Give us a list of steps in order to recreate the bug or crash.
      placeholder: |
        1. Do ...
        2. Then ...
        3. Do this ..., ... and then ...
        4. Observe "the bug" or "the crash"
    validations:
      required: true

  - type: textarea
    id: crash-log
    attributes:
      label: Errors
      description: Open the Developer Console with Ctrl/Cmd + Shift + i. Then look for any red errors (Ignore network errors like Failed to load resource) and paste them between the "```".
      value: |
        ```
        Replace this text with your crash-log.
        ```
    validations:
      required: false
