blank_issues_enabled: false
contact_links:
    - name: Vencord Support Server
      url: https://discord.gg/D9uwnFnqmd
      about: If you need help regarding Vencord, please join our support server!
    - name: PawsomeVencord Installer
      url: https://github.com/enzomtpYT/PawsomeVencordInstaller
      about: You can find the PawsomeVencord Installer here
