
export const strings = {
    "da": { "DISCONNECT_ALL": "Afbryd alle", "DISCONNECTED_ALL_USERS": "Afbrudt alle brugere fra Voice Channel: %d" },
    "de": { "DISCONNECT_ALL": "Alle trennen", "DISCONNECTED_ALL_USERS": "Alle Benutzer vom Voice Channel getrennt: %d" },
    "en-GB": { "DISCONNECT_ALL": "Disconnect All", "DISCONNECTED_ALL_USERS": "Disconnected all users from Voice Channel: %d" },
    "en-US": { "DISCONNECT_ALL": "Disconnect All", "DISCONNECTED_ALL_USERS": "Disconnected all users from Voice Channel: %d" },
    "es-ES": { "DISCONNECT_ALL": "Desconectar todo", "DISCONNECTED_ALL_USERS": "Todos los usuarios desconectados del canal de voz: %d" },
    "es-419": { "DISCONNECT_ALL": "Desconectar todo", "DISCONNECTED_ALL_USERS": "Todos los usuarios desconectados del canal de voz: %d" },
    "fr": { "DISCONNECT_ALL": "Tout déconnecter", "DISCONNECTED_ALL_USERS": "Tous les utilisateurs déconnectés du canal vocal : %d" },
    "hr": { "DISCONNECT_ALL": "Odspoji sve", "DISCONNECTED_ALL_USERS": "Svi korisnici su prekinuli vezu s glasovnim kanalom: %d" },
    "it": { "DISCONNECT_ALL": "Disconnetti tutto", "DISCONNECTED_ALL_USERS": "Tutti gli utenti sono stati disconnessi dal canale vocale: %d" },
    "lt": { "DISCONNECT_ALL": "Atjungti visus", "DISCONNECTED_ALL_USERS": "Visi vartotojai atjungti nuo balso kanalo: %d" },
    "hu": { "DISCONNECT_ALL": "Az összes leválasztása", "DISCONNECTED_ALL_USERS": "Az összes felhasználó leválasztva a hangcsatornáról: %d" },
    "nl": { "DISCONNECT_ALL": "Alles loskoppelen", "DISCONNECTED_ALL_USERS": "Alle gebruikers losgekoppeld van Voice Channel: %d" },
    "no": { "DISCONNECT_ALL": "Koble fra alle", "DISCONNECTED_ALL_USERS": "Alle brukere ble koblet fra talekanalen: %d" },
    "pl": { "DISCONNECT_ALL": "Odłącz wszystko", "DISCONNECTED_ALL_USERS": "Odłączono wszystkich użytkowników od kanału głosowego: %d" },
    "pt-BR": { "DISCONNECT_ALL": "Desconectar todos", "DISCONNECTED_ALL_USERS": "Desconectados todos os usuários do canal de voz: %d" },
    "ro": { "DISCONNECT_ALL": "Deconectați tot", "DISCONNECTED_ALL_USERS": "Toți utilizatorii au fost deconectați de la canalul vocal: %d" },
    "fi": { "DISCONNECT_ALL": "Katkaise kaikki yhteydet", "DISCONNECTED_ALL_USERS": "Kaikki käyttäjät on katkaistu äänikanavasta: %d" },
    "sv-SE": { "DISCONNECT_ALL": "Koppla från alla", "DISCONNECTED_ALL_USERS": "Kopplade bort alla användare från röstkanalen: %d" },
    "vi": { "DISCONNECT_ALL": "Ngắt kết nối tất cả", "DISCONNECTED_ALL_USERS": "Đã ngắt kết nối tất cả người dùng khỏi Kênh thoại: %d" },
    "tr": { "DISCONNECT_ALL": "Tümünün Bağlantısını Kes", "DISCONNECTED_ALL_USERS": "Tüm kullanıcıların Ses Kanalı ile bağlantısı kesildi: %d" },
    "cs": { "DISCONNECT_ALL": "Odpojit vše", "DISCONNECTED_ALL_USERS": "Všichni uživatelé byli odpojeni od hlasového kanálu: %d" },
    "el": { "DISCONNECT_ALL": "Αποσύνδεση όλων", "DISCONNECTED_ALL_USERS": "Αποσυνδέθηκαν όλοι οι χρήστες από το φωνητικό κανάλι: %d" },
    "bg": { "DISCONNECT_ALL": "Прекъснете връзката с всички", "DISCONNECTED_ALL_USERS": "Всички потребители са изключени от гласовия канал: %d" },
    "ru": { "DISCONNECT_ALL": "Отключить все", "DISCONNECTED_ALL_USERS": "Все пользователи отключены от голосового канала: %d" },
    "uk": { "DISCONNECT_ALL": "Відключити всіх", "DISCONNECTED_ALL_USERS": "Усіх користувачів відключено від голосового каналу: %d" },
    "hi": { "DISCONNECT_ALL": "सभी को डिस्कनेक्ट करें", "DISCONNECTED_ALL_USERS": "सभी उपयोगकर्ताओं को ध्वनि चैनल से डिस्कनेक्ट कर दिया गया: %d" },
    "th": { "DISCONNECT_ALL": "ตัดการเชื่อมต่อทั้งหมด", "DISCONNECTED_ALL_USERS": "ตัดการเชื่อมต่อผู้ใช้ทั้งหมดจากช่องสัญญาณเสียง: %d" },
    "zh-CN": { "DISCONNECT_ALL": "全部断开", "DISCONNECTED_ALL_USERS": "已断开所有用户与语音频道的连接：%d" },
    "ja": { "DISCONNECT_ALL": "すべて切断", "DISCONNECTED_ALL_USERS": "すべてのユーザーを音声チャンネルから切断しました: %d" },
    "zh-TW": { "DISCONNECT_ALL": "全部斷開", "DISCONNECTED_ALL_USERS": "已斷開所有使用者與語音頻道的連線：%d" },
    "ko": { "DISCONNECT_ALL": "모두 연결 끊기", "DISCONNECTED_ALL_USERS": "음성 채널에서 모든 사용자의 연결이 끊어졌습니다: %d" }
};
