/*
 * Vencord, a Discord client mod
 * Copyright (c) 2024 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { definePluginSettings } from "@api/Settings";
import { disableStyle } from "@api/Styles";
import { Devs } from "@utils/constants";
import definePlugin, { OptionType } from "@utils/types";

// Consolidated font family names
const fontFamilies: Record<string, string> = {
    "48fa8296-1c94-4c5e-841a-b7c32dbec095.ttf": "AdequateW05-Italic",
    "ABeeZee-Regular.ttf": "ABeeZee",
    "Adequate W01 Medium.ttf": "AdequateW01-Medium",
    "Adequate W01 Regular.ttf": "AdequateW01-Regular",
    "adequate-bold.ttf": "Adequate-Bold",
    "Adequate-ExtraLight.ttf": "Adequate",
    "adequate.extra-light.ttf": "Adequate",
    "Amazonas.ttf": "Amazonas",
    "AnonymousPro-Bold.ttf": "Anonymous Pro",
    "AnonymousPro-Regular.ttf": "Anonymous Pro",
    "AntipastoPro-Bold_trial.ttf": "Antipasto Pro Bold",
    "AntipastoPro-Extralight_trial.ttf": "Antipasto Pro Extralight",
    "Aotani-Bold.ttf": "Aotani Bold",
    "Aotani-ExtraBold.ttf": "Aotani Extra Bold",
    "Aotani-Light.ttf": "Aotani Light ",
    "Aotani-Medium.ttf": "Aotani Medium",
    "Arcon-Regular_MOD_by_zFontTool.ttf": "Arcon",
    "Arcon-Rounded-Regular_MOD_by_zFontTool.ttf": "Arcon Rounded-",
    "Arista-Pro-Alternate-Bold-trial.ttf": "Arista Pro Alternate Bold",
    "Arista-Pro-Alternate-ExtraLight-trial.ttf": "Arista Pro Alternate ExtraLight",
    "Arista-Pro-Bold-trial.ttf": "Arista Pro Bold",
    "Arista-Pro-ExtraLight-trial.ttf": "Arista Pro ExtraLight",
    "Aristotelica-Display-Bold-trial (1).ttf": "Aristotelica Display Trial",
    "Aristotelica-Display-Bold-trial.ttf": "Aristotelica Display Trial",
    "Aristotelica-Display-ExtraLight-trial.ttf": "Aristotelica Display Trial",
    "AvantGarde.ttf": "AvantGarde-Book Th",
    "AveriaLibre-Bold.ttf": "Averia Libre",
    "bariol_bold-webfont.ttf": "Bariol Bold",
    "Bellota-Bold.ttf": "Bellota",
    "Bellota-Light.ttf": "Bellota Light",
    "BeVietnamPro-Black.ttf": "Be Vietnam Pro Black",
    "BeVietnamPro-Bold.ttf": "Be Vietnam Pro",
    "BeVietnamPro-ExtraBold.ttf": "Be Vietnam Pro ExtraBold",
    "BeVietnamPro-ExtraLight.ttf": "Be Vietnam Pro ExtraLight",
    "BeVietnamPro-Light.ttf": "Be Vietnam Pro Light",
    "BeVietnamPro-Medium.ttf": "Be Vietnam Pro Medium",
    "BeVietnamPro-Regular.ttf": "Be Vietnam Pro",
    "BeVietnamPro-SemiBold.ttf": "Be Vietnam Pro SemiBold",
    "BeVietnamPro-Thin.ttf": "Be Vietnam Pro Thin",
    "Black Friday.ttf": "BlackFriday",
    "BonvenoCF-Light-webfont.ttf": "BonvenoCF",
    "BPreplay.ttf": "BPreplay",
    "Brie.ttf": "Brie Light",
    "cabin.bold.ttf": "Cabin",
    "cabin.medium.ttf": "Cabin",
    "cabin.regular.ttf": "Cabin",
    "cabin.semibold.ttf": "Cabin",
    "Caviar.ttf": "Caviar Dreams",
    "CaviarDreamBold.ttf": "Caviar Dreams",
    "CaviarDreams-Bofa.ttf": "Caviar Dreams",
    "CaviarDreams-Bold.ttf": "Caviar Dreams",
    "Caviardreams.ttf": "Caviar Dreams",
    "CaviarDreams_Bold.ttf": "Caviar Dreams",
    "Champagne & Limousines Bold.ttf": "Champagne & Limousines",
    "Champagne & Limousines.ttf": "Champagne & Limousines",
    "Cherry Monospace-Light.ttf": "Cherry",
    "CircularSpotifyTxT-Book.ttf": "Circular Spotify Tx T Book",
    "CircularSpotifyTxT-Light.ttf": "Circular Spotify Tx T Light",
    "Clockopia.ttf": "UKIJ Qolyazma",
    "ClockopiaBIG.ttf": "UKIJ Qolyazma",
    "Codec-Cold-Light-trial.ttf": "Codec Cold Trial",
    "Codec-Warm-Light-trial.ttf": "Codec Warm Trial",
    "CodecPro-Italic.ttf": "Codec Pro",
    "CodecPro-Regular.ttf": "Codec Pro",
    "Comfortaa-Bold.ttf": "Comfortaa",
    "Comfortaa-Light.ttf": "Comfortaa Light",
    "Comfortaa-Medium.ttf": "Comfortaa Medium",
    "Comfortaa-Regular.ttf": "Comfortaa",
    "Comfortaa-SemiBold.ttf": "Comfortaa SemiBold",
    "Comfortaa-VariableFont_wght.ttf": "Comfortaa",
    "Comforttta.ttf": "Comfortaa",
    "Convergence-Regular.ttf": "Convergence",
    "CormorantInfant-Bold.ttf": "Cormorant Infant",
    "CormorantInfant-Light.ttf": "Cormorant Infant Light",
    "CormorantInfant-Regular.ttf": "Cormorant Infant",
    "criticized.ttf": "Criticized",
    "cunt.ttf": "SF Pro Display",
    "DarkerGrotesque-Light.ttf": "Darker Grotesque Light",
    "Dearest.ttf": "Dearest",
    "debussy.ttf": "Debussy",
    "DejaVuSans.ttf": "DejaVu Sans",
    "Delius-Regular.ttf": "Delius",
    "DeliusSwashCaps-Regular.ttf": "Delius Swash Caps",
    "Deuglas.ttf": "Deuglas",
    "DidactGothic-Regular.ttf": "Didact Gothic",
    "editAdequate W01 Regular.ttf": "AdequateW01-Regular",
    "editComfortaa-Light.ttf": "Comfortaa Light",
    "editCormorantInfant-Regular.ttf": "Cormorant Infant",
    "EightOn.ttf": "Eight One",
    "EpicFusion.ttf": "Epic Fusion",
    "EXCITE__.ttf": "Excite",
    "Explora.ttf": "Explora",
    "Fabada-regular.ttf": "Fabada",
    "fak.ttf": "Spartan ExtraLight",
    "FontsFree-Net-SF-Pro-Rounded-Regular.ttf": "SF Pro Rounded",
    "FontsFree-Net-SF-UI-Display-Ultralight.ttf": "SF UI Display",
    "FontsFree-Net-SFProDisplay-Light.ttf": "SF Pro Display",
    "Forum-Regular.ttf": "Forum",
    "FredokaOne-Regular.ttf": "Fredoka One",
    "FugazOne-Regular.ttf": "Fugaz One",
    "Gasalt-Black.ttf": "Gasalt",
    "Gasalt-Regular.ttf": "Gasalt",
    "GeosansLight-Oblique.ttf": "GeosansLight",
    "GeosansLight.ttf": "GeosansLight",
    "GlacialIndifference-Bold.ttf": "Glacial Indifference",
    "GlacialIndifference-Regular.ttf": "Glacial Indifference",
    "Gruppo-Regular.ttf": "Gruppo",
    "GT-Walsheim-Bold.ttf": "GT Walsheim Bold",
    "HachiMaruPop-Regular.ttf": "Hachi Maru Pop",
    "hankenround-Regular.ttf": "hanken round",
    "Harmonia-Sans-W01-Semibold.ttf": "HarmoniaSansW01-Semibold",
    "HelloMissThang.ttf": "HelloMissThang",
    "HeroLight.ttf": "Hero Light",
    "HomemadeApple-Regular.ttf": "Homemade Apple",
    "Intimacy.ttf": "Intimacy",
    "Itim-Regular.ttf": "Itim",
    "JosefinSans-Bold.ttf": "Josefin Sans",
    "JosefinSans-ExtraLight.ttf": "Josefin Sans ExtraLight",
    "JosefinSans-Italic-VariableFont_wght.ttf": "Josefin Sans Thin",
    "JosefinSans-Light.ttf": "Josefin Sans Light",
    "JosefinSans-Medium.ttf": "Josefin Sans Medium",
    "JosefinSans-Regular.ttf": "Josefin Sans",
    "JosefinSans-SemiBold.ttf": "Josefin Sans SemiBold",
    "JosefinSans-SemiBoldItalic.ttf": "Josefin Sans SemiBold",
    "JosefinSans-Thin.ttf": "Josefin Sans Thin",
    "JosefinSans-VariableFont_wght.ttf": "Josefin Sans Thin",
    "JosefinSlab-ExtraLight.ttf": "Josefin Slab ExtraLight",
    "Jura-Bold.ttf": "Jura",
    "Jura-Light.ttf": "Jura Light",
    "Jura-Medium.ttf": "Jura Medium",
    "Jura-Regular.ttf": "Jura",
    "Jura-SemiBold.ttf": "Jura SemiBold",
    "Jura-VariableFont_wght.ttf": "Jura Light",
    "Kelvetica.ttf": "Kelvetica",
    "KGThinkingOutLoud.ttf": "KG Thinking Out Loud",
    "Lastwaerk black oblique.ttf": "Lastwaerk black",
    "Lastwaerk black.ttf": "Lastwaerk black",
    "Lastwaerk bold (1).ttf": "Lastwaerk bold",
    "Lastwaerk bold oblique.ttf": "Lastwaerk bold",
    "Lastwaerk bold.ttf": "Lastwaerk bold",
    "Lastwaerk light oblique.ttf": "Lastwaerk light",
    "Lastwaerk light.ttf": "Lastwaerk light",
    "Lastwaerk regular oblique.ttf": "Lastwaerk regular",
    "Lastwaerk regular.ttf": "Lastwaerk regular",
    "Lastwaerk thin oblique.ttf": "Lastwaerk thin",
    "Lastwaerk thin.ttf": "Lastwaerk thin",
    "Lato-Black.ttf": "Lato Black",
    "Lato-Light.ttf": "Lato Light",
    "Lato-Thin.ttf": "Lato Hairline",
    "LeagueSpartan-Black.ttf": "League Spartan Black",
    "LeagueSpartan-Bold.ttf": "League Spartan",
    "LeagueSpartan-ExtraBold.ttf": "League Spartan ExtraBold",
    "LeagueSpartan-ExtraLight.ttf": "League Spartan ExtraLight",
    "LeagueSpartan-Light.ttf": "League Spartan Light",
    "LeagueSpartan-Medium.ttf": "League Spartan Medium",
    "LeagueSpartan-Regular.ttf": "League Spartan",
    "LeagueSpartan-SemiBold.ttf": "League Spartan SemiBold",
    "LeagueSpartan-Thin.ttf": "League Spartan Thin",
    "LeagueSpartan-VariableFont_wght.ttf": "League Spartan Thin",
    "Lexend-Light.ttf": "Lexend Light",
    "Lexend-SemiBold.ttf": "Lexend SemiBold",
    "Livvic-Regular.ttf": "Livvic",
    "Livvic-SemiBold.ttf": "Livvic SemiBold",
    "LuxuriousRoman-Regular.ttf": "Luxurious Roman",
    "Mali-Light.ttf": "Mali Light",
    "Mali-Medium.ttf": "Mali Medium",
    "Mali-Regular.ttf": "Mali",
    "Mali-SemiBold.ttf": "Mali SemiBold",
    "Manjari-Bold.ttf": "Manjari",
    "Manjari-Regular.ttf": "Manjari",
    "Manjari-Thin.ttf": "Manjari Thin",
    "Merry Trace.ttf": "MerryTrace",
    "MGopenmoderna.ttf": "MgOpen Moderna",
    "Mitr-Light.ttf": "Mitr Light",
    "Mitr-Regular.ttf": "Mitr",
    "Mitr-SemiBold.ttf": "Mitr SemiBold",
    "MontserratAlternates-Regular.ttf": "Montserrat Alternates",
    "MuseoModerno-VariableFont_wght.ttf": "MuseoModerno SemiBold",
    "MuseoSans.ttf": "Museo Sans 500",
    "NanumPenScript-Regular.ttf": "Nanum Pen",
    "Neucha-Regular.ttf": "Neucha",
    "NewFont.ttf": "SF Pro Display",
    "Niramit-Bold.ttf": "Niramit Bold",
    "Niramit-Light.ttf": "Niramit Light",
    "Niramit-Regular.ttf": "Niramit",
    "Niramit-SemiBold.ttf": "Niramit SemiBold",
    "Nobile.ttf": "Nobile",
    "NovaScript-Regular.ttf": "Nova Script",
    "Octarine-Bold.ttf": "Octarine",
    "Octarine-BoldOblique.ttf": "Octarine",
    "Octarine-Light.ttf": "Octarine Light",
    "Octarine-LightOblique.ttf": "Octarine Light",
    "Oldenburg-Regular.ttf": "Oldenburg",
    "opificio_bold.ttf": "Opificio",
    "opificio_bold_rounded.ttf": "Opificio",
    "opificio_light.ttf": "Opificio",
    "opificio_light_rounded.ttf": "Opificio",
    "opificio_regular.ttf": "Opificio",
    "opificio_rounded.ttf": "Opificio",
    "PetitaBold.ttf": "PetitaBold",
    "PoiretOne-Regular.ttf": "Poiret One",
    "Poppins-ExtraLight.ttf": "Poppins ExtraLight",
    "Proxima-Nova-Soft-Semibold.ttf": "ProximaNovaSoft-Semibold",
    "Questrial-Regular.ttf": "Questrial",
    "Questrial_Regular.ttf": "Questrial",
    "Quicksand-Bold.ttf": "Quicksand",
    "Quicksand-Light.ttf": "Quicksand Light",
    "Quicksand-Medium.ttf": "Quicksand Medium",
    "Quicksand-Regular.ttf": "Quicksand",
    "Quicksand-SemiBold.ttf": "Quicksand SemiBold",
    "Quicksand-VariableFont_wght.ttf": "Quicksand Light",
    "Rajdhani-Light.ttf": "Rajdhani Light",
    "Rajdhani-Medium.ttf": "Rajdhani Medium",
    "Raleway-Bold.ttf": "Raleway",
    "Raleway-ExtraBold.ttf": "Raleway ExtraBold",
    "Raleway-ExtraLight.ttf": "Raleway ExtraLight",
    "Raleway-Light.ttf": "Raleway Light",
    "Raleway-Medium.ttf": "Raleway Medium",
    "Raleway-Regular.ttf": "Raleway",
    "Raleway-SemiBold.ttf": "Raleway SemiBold",
    "Raleway-Thin.ttf": "Raleway Thin",
    "Raleway-VariableFont_wght.ttf": "Raleway Thin",
    "ReportRg Regular.ttf": "Report Rg",
    "Righteous-Regular.ttf": "Righteous",
    "Roboto-Light.ttf": "Comfortaa",
    "Rounded_Elegance.ttf": "Rounded Elegance",
    "rounded_sans_serif_7.ttf": "Rounded Sans Serif 7",
    "Rubik-Light.ttf": "Rubik Light",
    "Rubik-Medium.ttf": "Rubik Medium",
    "Rubik-Regular.ttf": "Rubik",
    "Rubik-SemiBold.ttf": "Rubik SemiBold",
    "Rubik-VariableFont_wght.ttf": "Rubik Light",
    "SamsungOneUI-Bold.ttf": "SamsungOneUI",
    "SamsungOneUI-Regular.ttf": "SamsungOneUI",
    "secrcode.ttf": "Secret Code",
    "SecularOne-Regular.ttf": "Secular One",
    "SF-Pro-Display-Light.ttf": "SF Pro Display",
    "SF-Pro-Display-Medium.ttf": "SF Pro Display",
    "SF-Pro-Rounded-Medium.ttf": "SF Pro Rounded",
    "SF-Pro-Rounded-Semibold.ttf": "SF Pro Rounded",
    "SF-UI-Display-Ultralight.ttf": "SF UI Display",
    "SFCompactDisplay-Regular.ttf": "SF Compact Display",
    "SFGrandezza-Heavy.ttf": "SF Grandezza",
    "SFGrandezza-HeavyOblique.ttf": "SF Grandezza",
    "SFGrandezza-Light.ttf": "SF Grandezza",
    "SFGrandezza-LightOblique.ttf": "SF Grandezza",
    "SFGrandezza-Medium.ttf": "SF Grandezza",
    "SFGrandezza-MediumOblique.ttf": "SF Grandezza",
    "SFNewRepublic-Bold.ttf": "SF New Republic",
    "SFNewRepublic-high.ttf": "SF New Republic",
    "SFNewRepublic.ttf": "SF New Republic",
    "SFNewRepublicSC.ttf": "SF New Republic SC",
    "sforsoncasualheavy.ttf": "SF Orson Casual Heavy",
    "SFProDisplay-Light-BIG.ttf": "SF Pro Display",
    "SFProDisplay-Light.ttf": "SF Pro Display",
    "signoria.bold.ttf": "Signoria",
    "signoria.regular.ttf": "Signoria",
    "Simply Rounded Bold.ttf": "Simply Rounded",
    "Simply Rounded.ttf": "Simply Rounded",
    "SpaceMono-Regular.ttf": "Space Mono",
    "spar.ttf": "Spartan SemiBold",
    "Spartan-Black.ttf": "Spartan Black",
    "Spartan-Bold.ttf": "Spartan",
    "Spartan-ExtraBold.ttf": "Spartan ExtraBold",
    "Spartan-ExtraLight.ttf": "Spartan ExtraLight",
    "Spartan-Medium.ttf": "Spartan Medium",
    "Spartan.ttf": "Spartan Medium",
    "StarAv.ttf": "Star Avenue",
    "StintUltraExpanded-Regular.ttf": "Stint Ultra Expanded",
    "Street Corner Extend.ttf": "Street Corner Extend",
    "Street Corner Narrow.ttf": "Street Corner Narrow",
    "Street Corner SemiBold.ttf": "Street Corner SemiBold",
    "Street Corner Slab HyperExtend.ttf": "Street Corner Slab HyperExtend",
    "Street Corner Thin.ttf": "Street Corner Thin",
    "Street Corner.ttf": "Street Corner",
    "StudioGothic-ExtraBoldItalic Trial.ttf": "Studio Gothic Trial",
    "StudioGothicAlternate-ExtraLigh Trial.ttf": "Studio Gothic Alternate Trial",
    "SulphurPoint-Light.ttf": "Sulphur Point Light",
    "Syne-Bold.ttf": "Syne",
    "Syne-ExtraBold.ttf": "Syne ExtraBold",
    "Syne-Medium.ttf": "Syne Medium",
    "Syne-Regular.ttf": "Syne",
    "Syne-SemiBold.ttf": "Syne SemiBold",
    "Syne-VariableFont_wght (1).ttf": "Syne",
    "Syne-VariableFont_wght.ttf": "Syne",
    "SyneMono-Regular.ttf": "Syne Mono",
    "tecnico_bold.ttf": "Tecnico",
    "tecnico_regular.ttf": "Tecnico",
    "TextMeOne-Regular.ttf": "Text Me One",
    "timeburnerbold.ttf": "TimeBurner",
    "timeburnernormal.ttf": "TimeBurner",
    "Typo Grotesk Demo.otf.ttf": "Typo Grotesk",
    "UbuntuTitling-Bold.ttf": "Ubuntu Titling Rg",
    "Urbanist-Black.ttf": "Urbanist Black",
    "Urbanist-ExtraLight.ttf": "Urbanist ExtraLight",
    "Urbanist-VariableFont_wght.ttf": "Urbanist",
    "Winter.ttf": "Winter",
};

const fontOptions = Object.entries(fontFamilies).map(([value, label]) => ({
    label: label,
    value: value,
    default: false,
}));

const settings = definePluginSettings({
    selectedFont: {
        type: OptionType.SELECT,
        description: "Select a font",
        options: fontOptions,
    },
});

let fontStyleSheet: HTMLStyleElement | null = null;

const updateStyles = (selectedFont: string) => {
    const fontFamily = fontFamilies[selectedFont];

    if (!fontFamily) {
        console.error(`Font family not found for ${selectedFont}`);
        return;
    }

    if (!fontStyleSheet) {
        fontStyleSheet = document.createElement("style");
        document.head.appendChild(fontStyleSheet);
    }

    // Update the font-family property of the existing style sheet
    fontStyleSheet.textContent = `
        @font-face {
            font-family: '${fontFamily}';
            src: url('https://raw.githubusercontent.com/trebor048/discordddd/main/fonts/${selectedFont}');
            font-style: normal;
        }

        * {
            font-family: '${fontFamily}', sans-serif !important;
        }
    `;
};

export default definePlugin({
    name: "CustomFontPlugin",
    description: "Applies a custom font to the Discord window",
    authors: [Devs.Nuckyz],
    settings,

    start() {
        const { selectedFont } = settings.store;
        updateStyles(selectedFont);
    },

    stop() {
        if (fontStyleSheet) {
            disableStyle(fontStyleSheet.textContent || "");
            fontStyleSheet.remove();
            fontStyleSheet = null;
        }
    },

    update(selectedFont: string) {
        updateStyles(selectedFont);
    },
});
