/** Regenerates locales/registry.ts from JSON. */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..", "..");
const locales = join(root, "src", "plugins", "arabicUi", "locales");
const pluginsDir = join(locales, "plugins");
const discordDir = join(locales, "discord");
const outFile = join(locales, "registry.ts");

const pluginFiles = readdirSync(pluginsDir)
    .filter(f => f.endsWith(".json") && !f.startsWith("_"))
    .sort((a, b) => a.localeCompare(b));

const discordFiles = readdirSync(discordDir)
    .filter(f => f.endsWith(".json") && !f.startsWith("_"))
    .sort((a, b) => a.localeCompare(b));

const pluginImports = pluginFiles.map(f => {
    const id = f.replace(/\.json$/, "").replace(/[^a-zA-Z0-9_]/g, "_");
    return `import ${id} from "./plugins/${f}";`;
}).join("\n");

const discordImports = discordFiles.map((f, i) => {
    const id = `discord_${f.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]/g, "_")}`;
    return { id, f, line: `import ${id} from "./discord/${f}";` };
});

const header = `/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/**
 * AUTO-GENERATED by scripts/arabicUi/generateRegistry.mjs — do not edit by hand.
 * Add a JSON under locales/plugins/ then re-run the script.
 */

import type { DiscordLocalePack, PluginLocalePack } from "@plugins/arabicUi/types";

`;

// Map key must be the English definePlugin name (= filename without .json).
// JSON "name" is Arabic display only — never use it as the registry key.
const pluginData = pluginFiles.map(f => {
    const id = f.replace(/\.json$/, "").replace(/[^a-zA-Z0-9_]/g, "_");
    const name = f.replace(/\.json$/, "");
    return { id, f, name };
});

const body = `${discordImports.map(d => d.line).join("\n")}
${pluginImports}

export const discordPacks: DiscordLocalePack[] = [
${discordImports.map(d => `    ${d.id} as DiscordLocalePack,`).join("\n")}
];

export const pluginPacks: Record<string, PluginLocalePack> = {
${pluginData.map(p => {
        // Use JSON.stringify for keys with special chars
        const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(p.name) ? p.name : JSON.stringify(p.name);
        return `    ${key}: ${p.id} as PluginLocalePack,`;
    }).join("\n")}
};
`;

writeFileSync(outFile, header + body);
console.log(`Wrote ${outFile}`);
console.log(`  discord packs: ${discordFiles.length}`);
console.log(`  plugin packs: ${pluginFiles.length}`);

// sanity: JSON parses
for (const f of pluginFiles) {
    JSON.parse(readFileSync(join(pluginsDir, f), "utf8"));
}
console.log("All plugin JSON files OK");
