name: Sync Fork

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/Vendicated/Vencord"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
